name = "NARXEFEAgents"
uuid = "05f1177b-ce76-4d5b-ad16-16306cc08a77"
authors = ["wmkouw <wmkouw@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
